### ISSUE TITLE
decision making search record 404

### ISSUE THREAD

**Issue by vsoch** [poldracklab/cogat#123]
hey @rwblair ! I'm making some lesson content for using cogat, and I'm running into some bugs that I can report here (so maybe expect more!) The first is that searching for decision making the top hit looks like an old record:

![image](https://user-images.githubusercontent.com/814322/43690515-3a2fc786-98c0-11e8-94c0-6924c8f53980.png)

That actually I wouldn't want, because it's a bug:

![image](https://user-images.githubusercontent.com/814322/43690534-62808202-98c0-11e8-9983-b18f7e170df8.png)

but if you look down in the list, the correct one would be the one that ends in (concept)

**Comment by rwblair** [comment]
The drop down library was passing the search term to then results list for formatting. I couldn't figure out where or how that was happening, doesn't seem standard in other select2 examples I've seen.

Updated the 'selectFormat' function in the base template to ignore a search result that doesn't have a label, since we wouldn't be able to link to it properly. Should be good in production, but I haven't put the changes on github yet.

@vsoch Thank you for making an issue. If you notice any more wonkiness with this let me know.

**Comment by vsoch** [comment]
Awesome! Thanks for the speedy fix - I can confirm that the drop down works as expected now without the extra decision making listing:

![image](https://user-images.githubusercontent.com/814322/43729264-93f8539a-995c-11e8-86bd-b1a569dd39f0.png)

> @vsoch Thank you for making an issue. If you notice any more wonkiness with this let me know.

Will do!
