### ISSUE TITLE
Fix 'get' function test.

### ISSUE THREAD

**Issue by rwblair** [poldracklab/cogat#20]
Function takes id as an argument, but searches based on name. I'm not seeing get used in the atlas app.

**Comment by vsoch** [comment]
I don't think that's accurate - `self.name` refers to the kind of node, and the get function takes a field that is a variable to do the search on, see here:

https://github.com/poldracklab/cogat/blob/master/cognitive/apps/atlas/query.py#L217

It likely isn't used because the app was never developed beyond a skeleton :)

**Comment by rwblair** [comment]
Gotcha. I haven't seen it used any where.

**Comment by vsoch** [comment]
yep, that's pretty much the epitome of my graduate career - make a bunch of stuff and not use it :)
